#!/usr/bin/env python3
"""Fix trace references and regenerate index."""

import re
from pathlib import Path

CONV_DIR = Path(__file__).parent / "sessions" / "2026-01-03_introductiontoalgorithmsfourthedition"

# Mapping of conversation number to trace file
TRACE_MAP = {
    10: "TRACE-10-build-max-heap.md",
    13: "TRACE-13-quicksort.md",
    14: "TRACE-14-merge-sort.md",
    15: "TRACE-15-binary-search.md",
    16: "TRACE-16-red-black-tree.md",
    17: "TRACE-17-hash-table.md",
    18: "TRACE-18-binary-search-trees.md",
}


def fix_conversation_references():
    """Fix trace references in conversation files."""
    print("Fixing conversation file references...")
    
    for num, trace_file in TRACE_MAP.items():
        # Find the conversation file
        pattern = f"{num:02d}-*.md"
        matches = list(CONV_DIR.glob(pattern))
        
        if not matches:
            print(f"  ⚠️  No match for {pattern}")
            continue
        
        conv_file = matches[0]
        content = conv_file.read_text()
        
        # Replace any old TRACE reference with the correct one
        content = re.sub(
            r'\[`TRACE-[^\]]+\]',
            f'[`{trace_file}`]',
            content
        )
        content = re.sub(
            r'\]\(TRACE-[^)]+\.md\)',
            f']({trace_file})',
            content
        )
        
        conv_file.write_text(content)
        print(f"  ✅ {conv_file.name} → {trace_file}")


def regenerate_index():
    """Regenerate 00-index.md."""
    print("\nRegenerating index...")
    
    # Get all conversation files (excluding 00-index.md)
    conv_files = sorted([
        f for f in CONV_DIR.iterdir()
        if re.match(r'\d{2}-', f.name) and f.suffix == ".md" and not f.name.startswith("00-")
    ])
    
    # Get all trace files
    trace_files = {
        int(re.match(r'TRACE-(\d+)-', f.name).group(1)): f.name
        for f in CONV_DIR.iterdir()
        if f.name.startswith("TRACE-") and re.match(r'TRACE-(\d+)-', f.name)
    }
    
    index = """# 📚 Conversation Index

> **Session:** 2026-01-03 | Introduction to Algorithms (4th Edition)  
> **Total Entries:** {total}

---

## 📖 Q&A Entries

| # | Topic | Answer | Trace |
|--:|-------|--------|:-----:|
""".format(total=len(conv_files))
    
    for conv_file in conv_files:
        match = re.match(r'(\d+)-', conv_file.name)
        if not match:
            continue
        
        num = int(match.group(1))
        
        # Extract topic from filename
        topic = conv_file.name.replace(f"{num:02d}-2026-01-03-", "").replace(".md", "").replace("-", " ").title()[:40]
        
        # Get trace link
        trace_link = f"[📋]({trace_files[num]})" if num in trace_files else "-"
        
        index += f"| {num:02d} | {topic} | [📖]({conv_file.name}) | {trace_link} |\n"
    
    index += """
---

## 📊 Legend

| Symbol | Meaning |
|--------|---------|
| 📖 | Clean, formatted answer |
| 📋 | Full execution trace (debugging/auditing) |

---

## 📂 Files in this Session

### Answers (clean output)
- `NN-YYYY-MM-DD-topic.md` - Human-readable Q&A

### Traces (detailed logs)
- `TRACE-NN-topic.md` - Full RLM execution trace for auditing

---

*Generated by RLM Textbook Q&A*
"""
    
    (CONV_DIR / "00-index.md").write_text(index)
    print("  ✅ 00-index.md regenerated")


if __name__ == "__main__":
    fix_conversation_references()
    regenerate_index()
    print("\n✅ Done!")

